# Generated by Django 3.0.3 on 2020-03-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
