# Generated by Django 3.0.3 on 2020-03-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_hotel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='score',
            field=models.FloatField(blank=True, max_length=10, null=True),
        )
    ]
