# Generated by Django 3.0.3 on 2020-03-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_auto_20200310_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='latitude',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='longitude',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
